using HASmartCharge.Backend.DB.Models;
using Microsoft.EntityFrameworkCore;

namespace HASmartCharge.Backend.DB;

public class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
    {
    }

    public DbSet<HomeAssistantConnection> HomeAssistantConnections { get; set; }

    public DbSet<PriceProviderSettings> PriceProviderSettings { get; set; }
    public DbSet<CarSettings> CarSettings { get; set; }
    public DbSet<ChargerSettings> ChargerSettings { get; set; }
    public DbSet<HourlyPrice> HourlyPrices { get; set; }
    public DbSet<ChargePlan> ChargePlans { get; set; }
    public DbSet<ChargeSession> ChargeSessions { get; set; }
    public DbSet<HourlyEnergyUsage> HourlyEnergyUsage { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<HourlyPrice>()
            .HasKey(p => p.HourStartUtc);

        modelBuilder.Entity<ChargeSession>(session =>
        {
            // PK comes from the OCPP transaction id, never generated by the DB.
            session.HasKey(s => s.TransactionId);
            session.Property(s => s.TransactionId).ValueGeneratedNever();

            session.HasOne(s => s.Plan)
                .WithMany()
                .HasForeignKey(s => s.PlanId)
                .OnDelete(DeleteBehavior.SetNull);

            session.HasMany(s => s.HourlyUsage)
                .WithOne(u => u.Session)
                .HasForeignKey(u => u.SessionId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        // Settings tables are single-row, seeded with Id = 1.
        modelBuilder.Entity<PriceProviderSettings>().HasData(new PriceProviderSettings { Id = 1 });
        modelBuilder.Entity<CarSettings>().HasData(new CarSettings { Id = 1 });
        modelBuilder.Entity<ChargerSettings>().HasData(new ChargerSettings { Id = 1 });
    }
}
