// <auto-generated />
using System;
using HASmartCharge.Backend.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HASmartCharge.Backend.DB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260712134307_ChargePowerSlider")]
    partial class ChargePowerSlider
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.CarSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BatteryCapacityKwh")
                        .HasColumnType("REAL");

                    b.Property<double>("ChargeEfficiency")
                        .HasColumnType("REAL");

                    b.Property<string>("HaChargingStateEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HaPluggedInEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HaSocEntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HaStartDataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("HaStartDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HaStartService")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HaStopDataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("HaStopDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HaStopService")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HaTargetSocEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetSocPercent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CarSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatteryCapacityKwh = 75.0,
                            ChargeEfficiency = 0.90000000000000002,
                            HaSocEntityId = "",
                            HaStartDomain = "",
                            HaStartService = "",
                            HaStopDomain = "",
                            HaStopService = "",
                            Name = "My EV",
                            TargetSocPercent = 100
                        });
                });

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.ChargePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeadlineUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedEnergyKwh")
                        .HasColumnType("REAL");

                    b.Property<string>("SelectedHoursJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartSocPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetSocPercent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ChargePlans");
                });

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.ChargeSession", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChargePointId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSampleAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LastSampleKwh")
                        .HasColumnType("REAL");

                    b.Property<int>("MeterStartWh")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MeterStopWh")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalKwh")
                        .HasColumnType("REAL");

                    b.HasKey("TransactionId");

                    b.HasIndex("PlanId");

                    b.ToTable("ChargeSessions");
                });

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.ChargerSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChargePointId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ChargePowerMaxKw")
                        .HasColumnType("REAL");

                    b.Property<double>("ChargePowerMinKw")
                        .HasColumnType("REAL");

                    b.Property<double>("ChargePowerSetpointKw")
                        .HasColumnType("REAL");

                    b.Property<int>("ClockAlignedDataInterval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HeartbeatInterval")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxChargeKw")
                        .HasColumnType("REAL");

                    b.Property<int>("MeterValueSampleInterval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MeterValuesSampledData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChargerSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChargePointId = "",
                            ChargePowerMaxKw = 11.0,
                            ChargePowerMinKw = 1.3999999999999999,
                            ChargePowerSetpointKw = 11.0,
                            ClockAlignedDataInterval = 10,
                            ConnectorId = 1,
                            FriendlyName = "Charger",
                            HeartbeatInterval = 60,
                            MaxChargeKw = 11.0,
                            MeterValueSampleInterval = 10,
                            MeterValuesSampledData = "Power.Active.Import,Energy.Active.Import.Register,Current.Import,Voltage,Current.Offered,Power.Offered,SoC,Voltage.L1,Voltage.L2,Voltage.L3"
                        });
                });

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.HomeAssistantConnection", b =>
                {
                    b.Property<string>("BaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpiresIn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastRefreshedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BaseUrl");

                    b.ToTable("HomeAssistantConnections");
                });

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.HourlyEnergyUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<double>("EnergyKwh")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("HourStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerKwh")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("HourlyEnergyUsage");
                });

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.HourlyPrice", b =>
                {
                    b.Property<DateTime>("HourStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerKwh")
                        .HasColumnType("TEXT");

                    b.HasKey("HourStartUtc");

                    b.ToTable("HourlyPrices");
                });

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.PriceProviderSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RefreshMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierSlug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PriceProviderSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiUrl = "https://epexprijzen.nl/api/v1/prices/nextenergy/hourly",
                            Currency = "EUR",
                            RefreshMinutes = 60,
                            SupplierSlug = "nextenergy"
                        });
                });

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.ChargeSession", b =>
                {
                    b.HasOne("HASmartCharge.Backend.DB.Models.ChargePlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.HourlyEnergyUsage", b =>
                {
                    b.HasOne("HASmartCharge.Backend.DB.Models.ChargeSession", "Session")
                        .WithMany("HourlyUsage")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.ChargeSession", b =>
                {
                    b.Navigation("HourlyUsage");
                });
#pragma warning restore 612, 618
        }
    }
}
