// <auto-generated />
using System;
using HASmartCharge.Backend.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HASmartCharge.Backend.DB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260307150813_AddChargersConnectorsTransactions")]
    partial class AddChargersConnectorsTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.Charger", b =>
                {
                    b.Property<string>("ChargePointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastBootNotificationAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .HasColumnType("TEXT");

                    b.HasKey("ChargePointId");

                    b.ToTable("Chargers");
                });

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.ChargingTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChargePointId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdTag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MeterStartWh")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MeterStopWh")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StopReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdTag");

                    b.HasIndex("ChargePointId", "ConnectorId");

                    b.ToTable("ChargingTransactions");
                });

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.Connector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChargePointId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastStatusUpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChargePointId", "ConnectorId")
                        .IsUnique();

                    b.ToTable("Connectors");
                });

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.HomeAssistantConnection", b =>
                {
                    b.Property<string>("BaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpiresIn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastRefreshedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BaseUrl");

                    b.ToTable("HomeAssistantConnections");
                });

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.ChargingTransaction", b =>
                {
                    b.HasOne("HASmartCharge.Backend.DB.Models.Charger", "Charger")
                        .WithMany("Transactions")
                        .HasForeignKey("ChargePointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Charger");
                });

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.Connector", b =>
                {
                    b.HasOne("HASmartCharge.Backend.DB.Models.Charger", "Charger")
                        .WithMany("Connectors")
                        .HasForeignKey("ChargePointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Charger");
                });

            modelBuilder.Entity("HASmartCharge.Backend.DB.Models.Charger", b =>
                {
                    b.Navigation("Connectors");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
